environment:
  matrix:
    - RUBY_VERSION: "25"
    - RUBY_VERSION: "25-x64"

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

build_script:
  - bundle exec rake compile

test_script:
  - bundle exec rake
